<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Post extends Model
{
    protected $fillable = ['title', 'slug', 'content', 'online'];

    public function category(){
        return $this->belongsTo('App\Category');
    }
    /**
     * scope returns only online article and by DESC date (Last article first)
     * @param $query
     * @return mixed
     */
    public function scopePublished($query){
        return $query->where('online', true)->orderBy('created_at', 'desc');
    }

    /**
     * Reach article by title (only published article)
     * @param $q
     * @param $query
     * @return mixed
     */
    public function scopeSearchByTitle($q, $query){
        return $query->where('title', 'LIKE', '%'. $q . '%');
    }

    /**
     * Auto generation of the slug by taking the title if the slug is empty
     * @param $value
     */
    public function setSlugAttribute($value){
        if (empty($value)){
            $this->attributes['slug'] = Str::slug($this->title);
        }
    }

    /**
     * Change the route by ID to the slug
     * @return mixed
     */
//    public function getRouteKey()
//    {
//        return $this->slug; // TODO: Change the autogenerated stub
//    }
}
